### ISSUE TITLE
The cheat is not working

### ISSUE THREAD

**Issue by MadrisAkb** [Crack-House/nigusFN#3]
Whene i add m'y driver and i test thé aimbot/esp not working on thé game and m'y driver is UD what i update for thé esp/aimbot will work

**Comment by 0x00001337** [comment]
driver.h

**Comment by MadrisAkb** [comment]
> driver.h

Im added m'y driver and is working perfect but thé aimbot/esp not working on thé game also im updated all offsets is working with you or not?
